import type {
  EarthlyBranch,
  HeavenlyStem,
  Qi,
  SitianZaiquan,
  SixStepBoundaryTerm,
  SuiYun,
} from '../types.js';

export const RULE_VERSION = 'V1.0-2026.7.7-implementation.1' as const;

export const SIXTY_CYCLE = [
  '甲子',
  '乙丑',
  '丙寅',
  '丁卯',
  '戊辰',
  '己巳',
  '庚午',
  '辛未',
  '壬申',
  '癸酉',
  '甲戌',
  '乙亥',
  '丙子',
  '丁丑',
  '戊寅',
  '己卯',
  '庚辰',
  '辛巳',
  '壬午',
  '癸未',
  '甲申',
  '乙酉',
  '丙戌',
  '丁亥',
  '戊子',
  '己丑',
  '庚寅',
  '辛卯',
  '壬辰',
  '癸巳',
  '甲午',
  '乙未',
  '丙申',
  '丁酉',
  '戊戌',
  '己亥',
  '庚子',
  '辛丑',
  '壬寅',
  '癸卯',
  '甲辰',
  '乙巳',
  '丙午',
  '丁未',
  '戊申',
  '己酉',
  '庚戌',
  '辛亥',
  '壬子',
  '癸丑',
  '甲寅',
  '乙卯',
  '丙辰',
  '丁巳',
  '戊午',
  '己未',
  '庚申',
  '辛酉',
  '壬戌',
  '癸亥',
] as const;

export const STEM_RULES = {
  甲: { element: '土', state: '太过', tone: '太宫' },
  乙: { element: '金', state: '不及', tone: '少商' },
  丙: { element: '水', state: '太过', tone: '太羽' },
  丁: { element: '木', state: '不及', tone: '少角' },
  戊: { element: '火', state: '太过', tone: '太徵' },
  己: { element: '土', state: '不及', tone: '少宫' },
  庚: { element: '金', state: '太过', tone: '太商' },
  辛: { element: '水', state: '不及', tone: '少羽' },
  壬: { element: '木', state: '太过', tone: '太角' },
  癸: { element: '火', state: '不及', tone: '少徵' },
} as const satisfies Record<HeavenlyStem, SuiYun>;

export const BRANCH_QI_RULES = {
  子: { sitian: '少阴君火', zaiquan: '阳明燥金' },
  丑: { sitian: '太阴湿土', zaiquan: '太阳寒水' },
  寅: { sitian: '少阳相火', zaiquan: '厥阴风木' },
  卯: { sitian: '阳明燥金', zaiquan: '少阴君火' },
  辰: { sitian: '太阳寒水', zaiquan: '太阴湿土' },
  巳: { sitian: '厥阴风木', zaiquan: '少阳相火' },
  午: { sitian: '少阴君火', zaiquan: '阳明燥金' },
  未: { sitian: '太阴湿土', zaiquan: '太阳寒水' },
  申: { sitian: '少阳相火', zaiquan: '厥阴风木' },
  酉: { sitian: '阳明燥金', zaiquan: '少阴君火' },
  戌: { sitian: '太阳寒水', zaiquan: '太阴湿土' },
  亥: { sitian: '厥阴风木', zaiquan: '少阳相火' },
} as const satisfies Record<EarthlyBranch, SitianZaiquan>;

export const HOST_QI_SEQUENCE = [
  '厥阴风木',
  '少阴君火',
  '少阳相火',
  '太阴湿土',
  '阳明燥金',
  '太阳寒水',
] as const satisfies readonly Qi[];

export const GUEST_QI_SEQUENCE = [
  '厥阴风木',
  '少阴君火',
  '太阴湿土',
  '少阳相火',
  '阳明燥金',
  '太阳寒水',
] as const satisfies readonly Qi[];

export const STEP_BOUNDARY_TERMS = [
  '大寒',
  '春分',
  '小满',
  '大暑',
  '秋分',
  '小雪',
] as const satisfies readonly SixStepBoundaryTerm[];
